version: '3.8'

services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"  # For HTTP/3
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
    networks:
      - itsjustintv-network

  itsjustintv:
    image: ghcr.io/rmoriz/itsjustintv:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"  # Only accessible from localhost
    volumes:
      - ./data:/app/data
      - ./config.toml:/app/config.toml:ro
    environment:
      - ITSJUSTINTV_SERVER_LISTEN_ADDR=0.0.0.0
      - ITSJUSTINTV_SERVER_PORT=8080
      - ITSJUSTINTV_SERVER_EXTERNAL_DOMAIN=${DOMAIN:-localhost}
    networks:
      - itsjustintv-network
    depends_on:
      - caddy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  itsjustintv-network:
    driver: bridge